ALTER TABLE finansijski_plan_stavke
  ADD COLUMN IF NOT EXISTS osnov VARCHAR(40) NOT NULL DEFAULT 'fiksno' AFTER period,
  ADD COLUMN IF NOT EXISTS mesec_od TINYINT NOT NULL DEFAULT 1 AFTER iznos,
  ADD COLUMN IF NOT EXISTS mesec_do TINYINT NOT NULL DEFAULT 12 AFTER mesec_od,
  ADD COLUMN IF NOT EXISTS izvor VARCHAR(60) NULL AFTER predefinisana;
